In [ ]:
%matplotlib inline


In [ ]:
from __future__ import print_function
import torch
torch.__version__

'1.12.1+cu113'

# What is PyTorch?
- Python 기반 과학 연산 패키지로 다음과 같은 두 집단을 대상으로 함
- numpy를 대체하면서 GPU 연산이 필요한 경우
- 최대한 유연성과 속도를 제공하는 딥러닝 연구 플랫폼이 필요한 경우

# Getting Started
- Tensor는 numpy의 ndarray와 유사하며, 추가로 GPU를 사용한 연산 가속도 가능함

In [ ]:
# 초기화되지 않은 5x3 행렬 생성

x = torch.empty(5, 3)
print(x)

tensor([[9.9763e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])


In [ ]:
# 무작위로 초기화된 행렬 생성

x = torch.randn(5,3) # 표준정규분포에서 샘플링해서 값을 가져옴
print(x)
x = torch.rand(5,3) # 0~1에서 값을 랜덤으로 샘플링해서 값을 가져옴 (음수 값 없음)
print(x)

tensor([[ 0.7150,  0.6090,  0.0124],
        [ 0.5515, -0.6435, -1.5843],
        [ 0.7592, -1.5877,  0.4180],
        [ 0.3117,  0.1395,  0.0953],
        [ 0.3498,  2.4077,  0.4543]])
tensor([[0.2554, 0.0212, 0.7919],
        [0.4489, 0.3757, 0.9940],
        [0.1689, 0.6127, 0.1294],
        [0.6209, 0.3752, 0.2906],
        [0.9992, 0.6339, 0.6428]])


### dtype이 long이고, 0으로 채워진 행렬을 생성

In [ ]:
x = torch.zeros(5,3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [ ]:
x = torch.ones(5,3, dtype = torch.long)
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


### 데이터로부터 tensor를 직접 생성

In [ ]:
x = torch.tensor([5.5, 3]) # 벡터값 입력
print(x)

tensor([5.5000, 3.0000])


### 존재하는 tensor를 바탕으로 tensor를 만듦, 이 메서드(method)들은 사용자로부터 제공된 새로운 값이 없는 한, 입력 tensor의 속성들 (ex. dtype)을 재사용함

In [ ]:
x = x.new_ones(5,3, dtype= torch.double) # new * nethods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float) # override dtype! 
print(x)                                   # result has same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.3223, -1.0880, -0.0160],
        [-0.1405, -0.8578, -0.8183],
        [-0.2161,  0.2502,  1.1659],
        [-0.9843, -2.1470, -0.6663],
        [ 0.3440,  0.4274, -2.1768]])


### 행렬의 크기를 구하기

In [ ]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


### 덧셈 : 문법

In [ ]:
y = torch.rand(5,3)
print(x)
print(y)
print(x+y)

tensor([[-1.3223, -1.0880, -0.0160],
        [-0.1405, -0.8578, -0.8183],
        [-0.2161,  0.2502,  1.1659],
        [-0.9843, -2.1470, -0.6663],
        [ 0.3440,  0.4274, -2.1768]])
tensor([[0.3321, 0.5775, 0.1928],
        [0.0219, 0.3552, 0.2734],
        [0.9170, 0.4781, 0.5703],
        [0.1287, 0.3561, 0.9692],
        [0.9406, 0.1990, 0.0619]])
tensor([[-0.9902, -0.5105,  0.1768],
        [-0.1185, -0.5026, -0.5449],
        [ 0.7009,  0.7283,  1.7362],
        [-0.8556, -1.7909,  0.3030],
        [ 1.2846,  0.6265, -2.1150]])


In [ ]:
print(torch.add(x,y))

tensor([[-0.9902, -0.5105,  0.1768],
        [-0.1185, -0.5026, -0.5449],
        [ 0.7009,  0.7283,  1.7362],
        [-0.8556, -1.7909,  0.3030],
        [ 1.2846,  0.6265, -2.1150]])


### 덧셈 : 결과 tensor를 인자로 제공

In [ ]:
result = torch.empty(5,3) # 초기화되지 않은 tensor
print(result)

torch.add(x,y, out=result) # out 파라미터로 result를 지정
print(result) # 결과값이 tensor로 들어옴

tensor([[ 9.9765e-36,  0.0000e+00,  1.7682e-01],
        [-1.1855e-01, -5.0256e-01, -5.4493e-01],
        [ 7.0090e-01,  7.2825e-01,  1.7362e+00],
        [-8.5564e-01, -1.7909e+00,  3.0297e-01],
        [ 1.2846e+00,  6.2645e-01, -2.1150e+00]])
tensor([[-0.9902, -0.5105,  0.1768],
        [-0.1185, -0.5026, -0.5449],
        [ 0.7009,  0.7283,  1.7362],
        [-0.8556, -1.7909,  0.3030],
        [ 1.2846,  0.6265, -2.1150]])


### 덧셈 : 바꿔치기 (In-place) 형식

In [ ]:
# add x to y 
print(y)
y.add_(x)
print(y) # x가 +된 모습

tensor([[0.3321, 0.5775, 0.1928],
        [0.0219, 0.3552, 0.2734],
        [0.9170, 0.4781, 0.5703],
        [0.1287, 0.3561, 0.9692],
        [0.9406, 0.1990, 0.0619]])
tensor([[-0.9902, -0.5105,  0.1768],
        [-0.1185, -0.5026, -0.5449],
        [ 0.7009,  0.7283,  1.7362],
        [-0.8556, -1.7909,  0.3030],
        [ 1.2846,  0.6265, -2.1150]])


### Note
- 바꿔치기 방식으로 tensor의 값을 변경하는 연산은 _를 접미사로 갖는다.
- ex. x.copy_(y), x.t_()는 x를 변경한다.
- numpy스러운 인덱싱 표기방법을 사용할 수도 있다.

In [ ]:
print(x)
print(x[:, 1]) # 모든 행의 1번째 열

tensor([[-1.3223, -1.0880, -0.0160],
        [-0.1405, -0.8578, -0.8183],
        [-0.2161,  0.2502,  1.1659],
        [-0.9843, -2.1470, -0.6663],
        [ 0.3440,  0.4274, -2.1768]])
tensor([-1.0880, -0.8578,  0.2502, -2.1470,  0.4274])


### 크기변경 : tensor의 크기나 모양을 변경하고 싶으면 torch.view를 사용

In [ ]:
x = torch.randn(4,4)
print(x)

y = x.view(16) # 16개의 차원을 가진 벡터형태로 변환
z = y.view(-1, 2) # the size -1 is inferred from other dimensions (남는 원소를 자동으로 차원을 정해 넣어줘라) -> 2개씩 들어가니까 자동으로 2개씩 8개
print(y)
print(z)
print(y.size(), z.size())

tensor([[ 1.0331, -2.7639, -1.1657, -1.7601],
        [ 1.1753, -0.5830, -1.3325, -0.4675],
        [-0.1019, -1.0616,  0.6125, -0.3219],
        [ 1.7250, -0.0266,  0.3172, -2.8805]])
tensor([ 1.0331, -2.7639, -1.1657, -1.7601,  1.1753, -0.5830, -1.3325, -0.4675,
        -0.1019, -1.0616,  0.6125, -0.3219,  1.7250, -0.0266,  0.3172, -2.8805])
tensor([[ 1.0331, -2.7639],
        [-1.1657, -1.7601],
        [ 1.1753, -0.5830],
        [-1.3325, -0.4675],
        [-0.1019, -1.0616],
        [ 0.6125, -0.3219],
        [ 1.7250, -0.0266],
        [ 0.3172, -2.8805]])
torch.Size([16]) torch.Size([8, 2])


### 만약 tensor에 하나의 값만 존재한다면, item()을 사용하면 숫자값을 얻을 수 있음

In [ ]:
x = torch.randn(1)
print(x)
print(type(x), type(x.item()))
print(x.item())

tensor([-0.2843])
<class 'torch.Tensor'> <class 'float'>
-0.2842581570148468


### 참고사항
전치 transposing),인덱싱(indexing), 슬라이싱(slicing), 수학계산, 선형대수, 난수(rnadom number), 등과 같은 100가지 이상의 tensor 연산은 <http://pytorch.org/doc/torch>에서 설명함

### numpy 변환 (bridge)
torch tensor를 numpy 배열(array)로 변환하거나, 그 반대로 하는 것은 매우 쉬움
(cpu)상의 torch tensor와 numpy배열을 저장공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경됨
- torch tensor를 numpy로 변환하기

In [ ]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [ ]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


### numpy 배열의 값이 어떻게 변하는지 확인하기

In [ ]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [ ]:
temp = a.clone()
temp_numpy = temp.numpy()

a.add_(1)
print(a)
print(temp_numpy)

tensor([3., 3., 3., 3., 3.])
[2. 2. 2. 2. 2.]


### numpy 배열을 torch tensor로 변환하기
numpy 배열을 변경하면 torch tensor의 값도 자동으로 변경되는지 확인하기

In [ ]:
import numpy as np

a = np.ones(5)
print(a)

b = torch.from_numpy(a) # torch tensor변환
np.add(a, 1, out = a) # a에 1을 더하면 b도 변하는 모습
print(a)
print(b)

[1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### char tensor를 제외한 CPU상 모든 tensor는 numpy로의 변환을 지원하며, 반대변환도 지원함

# CUDA tensors
.to 메서드를 사용해 tensor를 어떠한 장치로 옮길 수 있음

In [ ]:
# 이 코드는 CUDA가 사용가능한 환경에서만 실행 
# ''torch.device''를 사용해 tensor를 GPU안팎으로 이동해본다.

x = torch.rand(4,4)

if torch.cuda.is_available(): # GPU가 이 세션에서 확인 가능한지 검사하는 것 (Trueㅇ리 때 아래 실행)
  device = "cuda:0" # torch.device("cuda:0") # CUDA 장치 객체(device object)로                ### GPU 0번째로 이동하겠다는 의미
  y = torch.ones_like(x, device=device)     # GPU 상에서 직접적으로 tensor를 생성하거나,
  print(y)

  x = x.to(device)                          # ''.to("cuda")''를 사용하면 됨 # CPU -> cuda 0번째로 이동
  z = x + y                                 # z는 x,y가 gpu이므로 자동으로 할당됨
  print(z)
  print(z.to("cpu", torch.double))         # ''.to''는 dtype도 함께 변경함

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0')
tensor([[1.4530, 1.0819, 1.7501, 1.1098],
        [1.5322, 1.8935, 1.9127, 1.1958],
        [1.0107, 1.7276, 1.0649, 1.6304],
        [1.2538, 1.4014, 1.8508, 1.1946]], device='cuda:0')
tensor([[1.4530, 1.0819, 1.7501, 1.1098],
        [1.5322, 1.8935, 1.9127, 1.1958],
        [1.0107, 1.7276, 1.0649, 1.6304],
        [1.2538, 1.4014, 1.8508, 1.1946]], dtype=torch.float64)


In [ ]:
x = x.cuda()