# 인공지능 수학 - 선형대수 (Numpy 실습)
## 행렬과 벡터의 코딩 및 연산

In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
A = np.array([[3, 1, 1], [1, -2, -1], [1, 1, 1]])

print(A)
print(np.shape(A))

[[ 3  1  1]
 [ 1 -2 -1]
 [ 1  1  1]]
(3, 3)


In [4]:
# Vector Cording
b =np.array([4, 1, 2])
print(b)
print(np.shape(b)) #3차원 벡터 표현

[4 1 2]
(3,)


In [6]:
# 역행렬 구하기
A_inv = np.linalg.inv(A)

print(A_inv)
print(np.shape(A_inv))

[[ 5.00000000e-01 -7.40148683e-17 -5.00000000e-01]
 [ 1.00000000e+00 -1.00000000e+00 -2.00000000e+00]
 [-1.50000000e+00  1.00000000e+00  3.50000000e+00]]
(3, 3)


In [8]:
# 역행렬을 이용한 선형시스템 Ax=b의 해 구하기
# x = np.matmul(A_inv, b)
# 행렬과 행렬, 행력과 벡터를 곱할 때 "@" 사용

x = A_inv @ b

print(x)
print(np.shape(x))

[ 1. -1.  2.]
(3,)


In [9]:
# 결과 검증
# bb - np.matmul(A, x)

bb = A @ x 
print(np.shape(bb))
print(bb)

# 벡터 norm (크기)이 10^-3 보다 작으면 True
if np.linalg.norm(b-bb) < 1e-3 :
    print("True")
else:
    print("somethoing wrong")

(3,)
[4. 1. 2.]
True
